[package]
name = "nrf52840-platform"
description = "Holistic embedded device support for nrf52840-based devices in a batteries-included manner"
documentation = "https://docs.rs/embedded-platform"
repository = "https://github.com/dflemstr/embedded-platform"
keywords = ["embedded", "platform", "io", "async", "nrf52"]
license = "MIT OR Apache-2.0"
categories = ["asynchronous", "embedded", "hardware-support", "no-std"]
version = "0.1.0"
authors = ["David Flemström <david.flemstrom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.3"
embedded-platform = { version = "0.1.0", path = "../.." }
nrf52840-hal = "0.8.1"

[dev-dependencies]
core = { package = "core-futures-tls", version = "0.1.1" }
cortex-m-rt = "0.6.11"
futures = { version = "0.3.1", default-features = false, features = ["async-await"] }
panic-halt = "0.2.0"
