[package]
name = "nrf52840-platform"
description = "Holistic embedded device support for nrf52840-based devices in a batteries-included manner"
documentation = "https://docs.rs/embedded-platform"
repository = "https://github.com/dflemstr/embedded-platform"
keywords = ["embedded", "platform", "io", "async", "nrf52"]
license = "MIT OR Apache-2.0"
categories = ["asynchronous", "embedded", "hardware-support", "no-std"]
version = "0.1.2"
authors = ["David Flemström <david.flemstrom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bare-metal = "0.2.5"
core = { package = "embedded-platform-core", path = "../../core" }
cortex-m = "0.6.1"
cortex-m-rt = "0.6.11"
direct-executor = "0.3.0"
embedded-hal = "0.2.3"
embedded-platform = { version = "0.1.0", path = "../.." }
nrf52840-hal = { git = "https://github.com/dflemstr/nrf52-hal.git", branch = "async-spi", default-features = false }

[dev-dependencies]
cortex-m-rt = "0.6.11"
futures = { version = "0.3.1", default-features = false }
panic-halt = "0.2.0"

[features]
default = ["rt"]
rt = ["nrf52840-hal/rt"]
